### ISSUE TITLE
powerfulseal fails while running pod scenario

### ISSUE THREAD

**Issue by iagusev** [krkn-chaos/krkn#165]
Hi!

I have standalone kraken installed on my VM and I'm trying to run pod scenario to kill pods in Openshift 3.11.
I faced the following issue:

```
2021-10-14 20:30:04 ERROR k8s_client (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': '70745aa7-6743-4983-a3ee-7e4bd3b9f743', 'Cache-Control': 'no-store', 'Content-Type': 'application/json', 'Date': 'Thu, 14 Oct 2021 17:30:05 GMT', 'Content-Length': '174'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}

Traceback (most recent call last):
  File "/home/centos/.local/lib/python3.6/site-packages/powerfulseal/k8s/k8s_client.py", line 231, in get_scenarios
    crds = self.client_extensionsApi.list_custom_resource_definition().to_dict()['items']
  File "/home/centos/.local/lib/python3.6/site-packages/kubernetes/client/api/apiextensions_v1_api.py", line 613, in list_custom_resource_definition
    return self.list_custom_resource_definition_with_http_info(**kwargs)  # noqa: E501
  File "/home/centos/.local/lib/python3.6/site-packages/kubernetes/client/api/apiextensions_v1_api.py", line 730, in list_custom_resource_definition_with_http_info
    collection_formats=collection_formats)
  File "/home/centos/.local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 353, in call_api
    _preload_content, _request_timeout, _host)
  File "/home/centos/.local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 184, in __call_api
    _request_timeout=_request_timeout)
  File "/home/centos/.local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 377, in request
    headers=headers)
  File "/home/centos/.local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 243, in GET
    query_params=query_params)
  File "/home/centos/.local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 233, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': '70745aa7-6743-4983-a3ee-7e4bd3b9f743', 'Cache-Control': 'no-store', 'Content-Type': 'application/json', 'Date': 'Thu, 14 Oct 2021 17:30:05 GMT', 'Content-Length': '174'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}


Traceback (most recent call last):
  File "/home/centos/.local/bin/powerfulseal", line 8, in <module>
    sys.exit(start())
  File "/home/centos/.local/lib/python3.6/site-packages/powerfulseal/cli/__main__.py", line 656, in start
    main(sys.argv[1:])
  File "/home/centos/.local/lib/python3.6/site-packages/powerfulseal/cli/__main__.py", line 630, in main
    metric_collector=metric_collector
  File "/home/centos/.local/lib/python3.6/site-packages/powerfulseal/policy/policy_runner.py", line 86, in run
    policy = self.read_policy()
  File "/home/centos/.local/lib/python3.6/site-packages/powerfulseal/policy/policy_runner.py", line 52, in read_policy
    scenarios = self.k8s_client.get_scenarios()
  File "/home/centos/.local/lib/python3.6/site-packages/powerfulseal/k8s/k8s_client.py", line 231, in get_scenarios
    crds = self.client_extensionsApi.list_custom_resource_definition().to_dict()['items']
  File "/home/centos/.local/lib/python3.6/site-packages/kubernetes/client/api/apiextensions_v1_api.py", line 613, in list_custom_resource_definition
    return self.list_custom_resource_definition_with_http_info(**kwargs)  # noqa: E501
  File "/home/centos/.local/lib/python3.6/site-packages/kubernetes/client/api/apiextensions_v1_api.py", line 730, in list_custom_resource_definition_with_http_info
    collection_formats=collection_formats)
  File "/home/centos/.local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 353, in call_api
    _preload_content, _request_timeout, _host)
  File "/home/centos/.local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 184, in __call_api
    _request_timeout=_request_timeout)
  File "/home/centos/.local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 377, in request
    headers=headers)
  File "/home/centos/.local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 243, in GET
    query_params=query_params)
  File "/home/centos/.local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 233, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': '70745aa7-6743-4983-a3ee-7e4bd3b9f743', 'Cache-Control': 'no-store', 'Content-Type': 'application/json', 'Date': 'Thu, 14 Oct 2021 17:30:05 GMT', 'Content-Length': '174'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}


2021-10-14 20:30:05,087 [ERROR] Failed to run powerfulseal autonomous --use-pod-delete-instead-of-ssh-kill --policy-file scenarios/customapp_pod.yaml --kubeconfig /home/centos/.kube/config --no-cloud --inventory-kubernetes --headless, error: Command 'powerfulseal autonomous --use-pod-delete-instead-of-ssh-kill --policy-file scenarios/customapp_pod.yaml --kubeconfig /home/centos/.kube/config --no-cloud --inventory-kubernetes --headless' returned non-zero exit status 1.
```

Scenario I run:

```
config:
  runStrategy:
    runs: 1
    maxSecondsBetweenRuns: 30
    minSecondsBetweenRuns: 1
scenarios:
  - name: "delete glusterfs pods"
    steps:
    - podAction:
        matches:
          - labels:
              namespace: "glusterfs"
              selector: ""
        filters:
          - property:
              name: "state"
              value: "Running"
          - randomSample:
              size: 1
        actions:
          - kill:
              probability: 1
              force: true
    - podAction:
        matches:
          - labels:
              namespace: "glusterfs"
              selector: ""
        retries:
          retriesTimeout:
            timeout: 180

        actions:
          - checkPodCount:
              count: 5
```
Cluster works, and responses:

```
NAME                                          READY   STATUS    RESTARTS   AGE
glusterblock-storage-provisioner-dc-1-q59xs   1/1     Running   0          6d
glusterfs-storage-jgv6n                       1/1     Running   0          6d
glusterfs-storage-mlgmr                       1/1     Running   0          15d
glusterfs-storage-zkf5n                       1/1     Running   0          6d
heketi-storage-2-xckf4                        1/1     Running   0          52d
```

Should I create an issue in powerfulseal github, or it might be an issue in internal kraken logic?

Thank you!

**Comment by sinamas1** [comment]
Hi @chaitanyaenr ,

I'm facing this error while running the pod scenario. Can you please confirm if this solution is still relevant to the new version of the Kraken tool as well?

HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}
