### ISSUE TITLE
Support to add custom CA certs

### ISSUE THREAD

**Issue by harshil-codes** [krkn-chaos/krkn#275]
If kraken is relying on cerberus to get cluster health and cerberus service is exposed as a openshift route or running somewhere else, kraken fails to securely connect to the cerberus service through the route if there are private or self-signed certs involved. 

Python throws the "CERTIFICATE_VERIFY_FAILED". Invoking the system certs which contain the self-signed/private before kraken service is started could resolve this.

**Comment by enginecoremx** [comment]
I have the kind of same issue. My certificates are signed by  a valid CA even dough I received the same error

```
krkn) [alex@bastion krkn]$ oc get clusterversion
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.10.34   True        False         18d     Cluster version is 4.10.34
(krkn) [alex@bastion krkn]$

```
Output 

```

(krkn) [alex@bastion krkn]$
(krkn) [alex@bastion krkn]$ python run_kraken.py --config config/config.yaml
 _              _
| | ___ __ __ _| | _____ _ __
| |/ / '__/ _` | |/ / _ \ '_ \
|   <| | | (_| |   <  __/ | | |
|_|\_\_|  \__,_|_|\_\___|_| |_|


2022-11-28 00:03:21,070 [INFO] Starting kraken
2022-11-28 00:03:21,089 [INFO] Initializing client to talk to the Kubernetes cluster
2022-11-28 00:03:21,189 [WARNING] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1129)'))': /version
2022-11-28 00:03:21,201 [WARNING] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1129)'))': /version
2022-11-28 00:03:21,213 [WARNING] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1129)'))': /version
Traceback (most recent call last):
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/urllib3/connection.py", line 337, in connect
    self.sock = ssl_wrap_socket(
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 345, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/alex/.pyenv/versions/3.9-dev/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/alex/.pyenv/versions/3.9-dev/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/home/alex/.pyenv/versions/3.9-dev/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alex/openshift/test/krkn/run_kraken.py", line 429, in <module>
    main(options.cfg)
  File "/home/alex/openshift/test/krkn/run_kraken.py", line 105, in main
    kubecli.initialize_clients(kubeconfig_path)
  File "/home/alex/openshift/test/krkn/kraken/kubernetes/client.py", line 34, in initialize_clients
    dyn_client = DynamicClient(k8s_client)
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/kubernetes/dynamic/client.py", line 84, in __init__
    self.__discoverer = discoverer(self, cache_file)
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/kubernetes/dynamic/discovery.py", line 224, in __init__
    Discoverer.__init__(self, client, cache_file)
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/kubernetes/dynamic/discovery.py", line 50, in __init__
    self.__init_cache()
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/kubernetes/dynamic/discovery.py", line 66, in __init_cache
    self._load_server_info()
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/kubernetes/dynamic/discovery.py", line 141, in _load_server_info
    'kubernetes': self.client.request('get', '/version', serializer=just_json)
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/kubernetes/dynamic/client.py", line 55, in inner
    resp = func(self, *args, **kwargs)
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/kubernetes/dynamic/client.py", line 270, in request
    api_response = self.client.call_api(
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/kubernetes/client/rest.py", line 241, in GET
    return self.request("GET", url,
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/kubernetes/client/rest.py", line 214, in request
    r = self.pool_manager.request(method, url,
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/urllib3/request.py", line 66, in request
    return self.request_encode_url(method, url, fields=fields,
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/urllib3/request.py", line 89, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/urllib3/poolmanager.py", line 324, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/urllib3/connectionpool.py", line 663, in urlopen
    return self.urlopen(method, url, body, headers, retries,
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/urllib3/connectionpool.py", line 663, in urlopen
    return self.urlopen(method, url, body, headers, retries,
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/urllib3/connectionpool.py", line 663, in urlopen
    return self.urlopen(method, url, body, headers, retries,
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/urllib3/connectionpool.py", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.openshift.training', port=6443): Max retries exceeded with url: /version (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1129)')))
(krkn) [alex@bastion krkn]$ curl -IL https://api.openshift.training:6443
HTTP/2 403
audit-id: 610c0550-406d-4700-a544-51a18f244122
cache-control: no-cache, private
content-type: application/json
x-content-type-options: nosniff
x-kubernetes-pf-flowschema-uid: 9cdc4a51-2a2b-42ea-a1fe-512c8f2833b5
x-kubernetes-pf-prioritylevel-uid: fa99e8d5-97b8-4980-88f7-933a5aded549
content-length: 218
date: Mon, 28 Nov 2022 05:03:41 GMT

(krkn) [alex@bastion krkn]$ curl  https://api.openshift.training:6443
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}(krkn) [alex@bastion krkn]$ python --version
Python 3.9.15+
(krkn) [alex@bastion krkn]$ oc get nodes
NAME                           STATUS   ROLES          AGE    VERSION
openshift-dph56-infra-hfrzw    Ready    infra,worker   18d    v1.23.5+8471591
openshift-dph56-infra-pjtkn    Ready    infra,worker   18d    v1.23.5+8471591
openshift-dph56-infra-wq8tf    Ready    infra,worker   18d    v1.23.5+8471591
openshift-dph56-master-0       Ready    master         18d    v1.23.5+8471591
openshift-dph56-master-2       Ready    master         18d    v1.23.5+8471591
openshift-dph56-master-3       Ready    master         5d8h   v1.23.5+8471591
openshift-dph56-worker-2w8xk   Ready    worker         18d    v1.23.5+8471591
openshift-dph56-worker-9v769   Ready    worker         18d    v1.23.5+8471591
openshift-dph56-worker-qgx5r   Ready    worker         18d    v1.23.5+8471591
(krkn) [alex@bastion krkn]$
```

**Comment by alexgdmx** [comment]
I have kind of the same issue. My certificates are signed by  a valid CA even tho I received the same error

```
(krkn) [alex@bastion krkn]$ oc get clusterversion
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.10.34   True        False         18d     Cluster version is 4.10.34
(krkn) [alex@bastion krkn]$

```
Output 
```
(krkn) [alex@bastion krkn]$
(krkn) [alex@bastion krkn]$ python run_kraken.py --config config/config.yaml
 _              _
| | ___ __ __ _| | _____ _ __
| |/ / '__/ _` | |/ / _ \ '_ \
|   <| | | (_| |   <  __/ | | |
|_|\_\_|  \__,_|_|\_\___|_| |_|


2022-11-28 00:03:21,070 [INFO] Starting kraken
2022-11-28 00:03:21,089 [INFO] Initializing client to talk to the Kubernetes cluster
2022-11-28 00:03:21,189 [WARNING] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1129)'))': /version
2022-11-28 00:03:21,201 [WARNING] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1129)'))': /version
2022-11-28 00:03:21,213 [WARNING] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1129)'))': /version
Traceback (most recent call last):
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/urllib3/connection.py", line 337, in connect
    self.sock = ssl_wrap_socket(
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 345, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/alex/.pyenv/versions/3.9-dev/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/alex/.pyenv/versions/3.9-dev/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/home/alex/.pyenv/versions/3.9-dev/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alex/openshift/test/krkn/run_kraken.py", line 429, in <module>
    main(options.cfg)
  File "/home/alex/openshift/test/krkn/run_kraken.py", line 105, in main
    kubecli.initialize_clients(kubeconfig_path)
  File "/home/alex/openshift/test/krkn/kraken/kubernetes/client.py", line 34, in initialize_clients
    dyn_client = DynamicClient(k8s_client)
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/kubernetes/dynamic/client.py", line 84, in __init__
    self.__discoverer = discoverer(self, cache_file)
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/kubernetes/dynamic/discovery.py", line 224, in __init__
    Discoverer.__init__(self, client, cache_file)
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/kubernetes/dynamic/discovery.py", line 50, in __init__
    self.__init_cache()
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/kubernetes/dynamic/discovery.py", line 66, in __init_cache
    self._load_server_info()
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/kubernetes/dynamic/discovery.py", line 141, in _load_server_info
    'kubernetes': self.client.request('get', '/version', serializer=just_json)
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/kubernetes/dynamic/client.py", line 55, in inner
    resp = func(self, *args, **kwargs)
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/kubernetes/dynamic/client.py", line 270, in request
    api_response = self.client.call_api(
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/kubernetes/client/rest.py", line 241, in GET
    return self.request("GET", url,
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/kubernetes/client/rest.py", line 214, in request
    r = self.pool_manager.request(method, url,
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/urllib3/request.py", line 66, in request
    return self.request_encode_url(method, url, fields=fields,
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/urllib3/request.py", line 89, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/urllib3/poolmanager.py", line 324, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/urllib3/connectionpool.py", line 663, in urlopen
    return self.urlopen(method, url, body, headers, retries,
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/urllib3/connectionpool.py", line 663, in urlopen
    return self.urlopen(method, url, body, headers, retries,
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/urllib3/connectionpool.py", line 663, in urlopen
    return self.urlopen(method, url, body, headers, retries,
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/urllib3/connectionpool.py", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/home/alex/.pyenv/versions/krkn/lib/python3.9/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.openshift.training', port=6443): Max retries exceeded with url: /version (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1129)')))
(krkn) [alex@bastion krkn]$ curl -IL https://api.openshift.training:6443
HTTP/2 403
audit-id: 610c0550-406d-4700-a544-51a18f244122
cache-control: no-cache, private
content-type: application/json
x-content-type-options: nosniff
x-kubernetes-pf-flowschema-uid: 9cdc4a51-2a2b-42ea-a1fe-512c8f2833b5
x-kubernetes-pf-prioritylevel-uid: fa99e8d5-97b8-4980-88f7-933a5aded549
content-length: 218
date: Mon, 28 Nov 2022 05:03:41 GMT

curl doesn't have issues with the CA
(krkn) [alex@bastion krkn]$ curl  https://api.openshift.training:6443
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
```

Python version:
```
(krkn) [alex@bastion krkn]$ python --version
Python 3.9.15+

```
oc client works fine
```
(krkn) [alex@bastion krkn]$ oc get nodes
NAME                           STATUS   ROLES          AGE    VERSION
openshift-dph56-infra-hfrzw    Ready    infra,worker   18d    v1.23.5+8471591
openshift-dph56-infra-pjtkn    Ready    infra,worker   18d    v1.23.5+8471591
openshift-dph56-infra-wq8tf    Ready    infra,worker   18d    v1.23.5+8471591
openshift-dph56-master-0       Ready    master         18d    v1.23.5+8471591
openshift-dph56-master-2       Ready    master         18d    v1.23.5+8471591
openshift-dph56-master-3       Ready    master         5d8h   v1.23.5+8471591
openshift-dph56-worker-2w8xk   Ready    worker         18d    v1.23.5+8471591
openshift-dph56-worker-9v769   Ready    worker         18d    v1.23.5+8471591
openshift-dph56-worker-qgx5r   Ready    worker         18d    v1.23.5+8471591
(krkn) [alex@bastion krkn]$

```
