### ISSUE TITLE
Getting ssl.SSLCertVerificationError

### ISSUE THREAD

**Issue by AtulTodi** [krkn-chaos/krkn#282]
I am getting below error while trying to run kraken in standalone mode.

Config file: 

apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://openshift:6443
  name: openshift:6443
contexts:
- context:
    cluster: openshift:6443
    namespace: default
    user: atodi
  name: default/openshift/atodi
current-context: default/openshift:6443/atodi
kind: Config
preferences: {}
users:
- name: atodi
  user:
    token: token

Error:

(chaos) MLRW20108535:krkn atodi$ python3 run_kraken.py --config ./config.yaml 
 _              _              
| | ___ __ __ _| | _____ _ __  
| |/ / '__/ _` | |/ / _ \ '_ \ 
|   <| | | (_| |   <  __/ | | |
|_|\_\_|  \__,_|_|\_\___|_| |_|
                               

2022-07-27 10:32:06,501 [INFO] Starting kraken
2022-07-27 10:32:06,507 [INFO] Initializing client to talk to the Kubernetes cluster
2022-07-27 10:32:06,726 [WARNING] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)'))': /version
2022-07-27 10:32:06,852 [WARNING] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)'))': /version
2022-07-27 10:32:06,975 [WARNING] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)'))': /version
Traceback (most recent call last):
  File "/Users/atodi/Documents/ocp/chaos/krkn/chaos/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/atodi/Documents/ocp/chaos/krkn/chaos/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/atodi/Documents/ocp/chaos/krkn/chaos/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/atodi/Documents/ocp/chaos/krkn/chaos/lib/python3.9/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/atodi/Documents/ocp/chaos/krkn/chaos/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/atodi/Documents/ocp/chaos/krkn/chaos/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/atodi/Documents/ocp/chaos/krkn/run_kraken.py", line 318, in <module>
    main(options.cfg)
  File "/Users/atodi/Documents/ocp/chaos/krkn/run_kraken.py", line 78, in main
    kubecli.initialize_clients(kubeconfig_path)
  File "/Users/atodi/Documents/ocp/chaos/krkn/kraken/kubernetes/client.py", line 29, in initialize_clients
    dyn_client = DynamicClient(k8s_client)
  File "/Users/atodi/Documents/ocp/chaos/krkn/chaos/lib/python3.9/site-packages/kubernetes/dynamic/client.py", line 84, in __init__
    self.__discoverer = discoverer(self, cache_file)
  File "/Users/atodi/Documents/ocp/chaos/krkn/chaos/lib/python3.9/site-packages/kubernetes/dynamic/discovery.py", line 224, in __init__
    Discoverer.__init__(self, client, cache_file)
  File "/Users/atodi/Documents/ocp/chaos/krkn/chaos/lib/python3.9/site-packages/kubernetes/dynamic/discovery.py", line 50, in __init__
    self.__init_cache()
  File "/Users/atodi/Documents/ocp/chaos/krkn/chaos/lib/python3.9/site-packages/kubernetes/dynamic/discovery.py", line 66, in __init_cache
    self._load_server_info()
  File "/Users/atodi/Documents/ocp/chaos/krkn/chaos/lib/python3.9/site-packages/kubernetes/dynamic/discovery.py", line 141, in _load_server_info
    'kubernetes': self.client.request('get', '/version', serializer=just_json)
  File "/Users/atodi/Documents/ocp/chaos/krkn/chaos/lib/python3.9/site-packages/kubernetes/dynamic/client.py", line 55, in inner
    resp = func(self, *args, **kwargs)
  File "/Users/atodi/Documents/ocp/chaos/krkn/chaos/lib/python3.9/site-packages/kubernetes/dynamic/client.py", line 247, in request
    return self.client.call_api(
  File "/Users/atodi/Documents/ocp/chaos/krkn/chaos/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/Users/atodi/Documents/ocp/chaos/krkn/chaos/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/Users/atodi/Documents/ocp/chaos/krkn/chaos/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/Users/atodi/Documents/ocp/chaos/krkn/chaos/lib/python3.9/site-packages/kubernetes/client/rest.py", line 239, in GET
    return self.request("GET", url,
  File "/Users/atodi/Documents/ocp/chaos/krkn/chaos/lib/python3.9/site-packages/kubernetes/client/rest.py", line 212, in request
    r = self.pool_manager.request(method, url,
  File "/Users/atodi/Documents/ocp/chaos/krkn/chaos/lib/python3.9/site-packages/urllib3/request.py", line 74, in request
    return self.request_encode_url(
  File "/Users/atodi/Documents/ocp/chaos/krkn/chaos/lib/python3.9/site-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/Users/atodi/Documents/ocp/chaos/krkn/chaos/lib/python3.9/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/atodi/Documents/ocp/chaos/krkn/chaos/lib/python3.9/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/Users/atodi/Documents/ocp/chaos/krkn/chaos/lib/python3.9/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/Users/atodi/Documents/ocp/chaos/krkn/chaos/lib/python3.9/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/Users/atodi/Documents/ocp/chaos/krkn/chaos/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/atodi/Documents/ocp/chaos/krkn/chaos/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.aws-useast1-apps-lab-2.ocpdev.us-east-1.ac.discoverfinancial.com', port=6443): Max retries exceeded with url: /version (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)')))

**Comment by alexgdmx** [comment]
It happen also in the container version

**Comment by tsebastiani** [comment]
please check the documentation: https://krkn-chaos.dev/docs/debugging/#ssl-certification, closing.
